name: "Automated Documentation Generator Labels"
description: "Labels for the Automated Documentation Generator project"
color: "0e8a16"
labels:
  # Priority Labels
  - name: "priority: critical"
    description: "Critical priority - must be addressed immediately"
    color: "d73a4a"
  - name: "priority: high"
    description: "High priority - should be addressed soon"
    color: "f85149"
  - name: "priority: medium"
    description: "Medium priority - should be addressed in reasonable time"
    color: "fbca04"
  - name: "priority: low"
    description: "Low priority - can be addressed when time permits"
    color: "0e8a16"

  # Type Labels
  - name: "type: bug"
    description: "Something isn't working"
    color: "d73a4a"
  - name: "type: enhancement"
    description: "New feature or request"
    color: "a2eeef"
  - name: "type: documentation"
    description: "Improvements or additions to documentation"
    color: "0075ca"
  - name: "type: question"
    description: "Further information is requested"
    color: "d876e3"
  - name: "type: discussion"
    description: "Discussion or brainstorming"
    color: "7057ff"

  # Status Labels
  - name: "status: needs-triage"
    description: "Needs to be triaged and categorized"
    color: "f9d0c4"
  - name: "status: in-progress"
    description: "Work in progress"
    color: "fbca04"
  - name: "status: blocked"
    description: "Blocked by another issue or dependency"
    color: "d73a4a"
  - name: "status: on-hold"
    description: "Temporarily paused"
    color: "f85149"
  - name: "status: ready-for-review"
    description: "Ready for code review"
    color: "0e8a16"
  - name: "status: needs-feedback"
    description: "Needs feedback from maintainers or community"
    color: "fbca04"

  # Component Labels
  - name: "component: cli"
    description: "Command-line interface"
    color: "c5def5"
  - name: "component: core"
    description: "Core functionality"
    color: "c5def5"
  - name: "component: search"
    description: "Semantic search functionality"
    color: "c5def5"
  - name: "component: generator"
    description: "Documentation generation"
    color: "c5def5"
  - name: "component: api"
    description: "Programmatic API"
    color: "c5def5"
  - name: "component: ui"
    description: "User interface"
    color: "c5def5"
  - name: "component: tests"
    description: "Tests and testing infrastructure"
    color: "c5def5"
  - name: "component: docs"
    description: "Documentation"
    color: "c5def5"
  - name: "component: ci-cd"
    description: "CI/CD pipeline"
    color: "c5def5"
  - name: "component: docker"
    description: "Docker and containerization"
    color: "c5def5"

  # Technology Labels
  - name: "tech: typescript"
    description: "TypeScript related"
    color: "3178c6"
  - name: "tech: nodejs"
    description: "Node.js related"
    color: "339933"
  - name: "tech: openai"
    description: "OpenAI API related"
    color: "412991"
  - name: "tech: docker"
    description: "Docker related"
    color: "2496ed"
  - name: "tech: jest"
    description: "Jest testing framework"
    color: "c21325"
  - name: "tech: eslint"
    description: "ESLint related"
    color: "4b32c3"
  - name: "tech: prettier"
    description: "Prettier related"
    color: "f7b93e"

  # Difficulty Labels
  - name: "difficulty: easy"
    description: "Good for newcomers"
    color: "0e8a16"
  - name: "difficulty: medium"
    description: "Requires some experience"
    color: "fbca04"
  - name: "difficulty: hard"
    description: "Requires significant experience"
    color: "d73a4a"

  # Size Labels
  - name: "size: xs"
    description: "Extra small - < 10 lines"
    color: "0e8a16"
  - name: "size: s"
    description: "Small - 10-50 lines"
    color: "0e8a16"
  - name: "size: m"
    description: "Medium - 50-200 lines"
    color: "fbca04"
  - name: "size: l"
    description: "Large - 200-500 lines"
    color: "f85149"
  - name: "size: xl"
    description: "Extra large - > 500 lines"
    color: "d73a4a"

  # Special Labels
  - name: "good first issue"
    description: "Good for newcomers"
    color: "7057ff"
  - name: "help wanted"
    description: "Extra attention is needed"
    color: "008672"
  - name: "wontfix"
    description: "This will not be worked on"
    color: "ffffff"
  - name: "duplicate"
    description: "This issue or pull request already exists"
    color: "cfd3d7"
  - name: "invalid"
    description: "This doesn't seem right"
    color: "e4e669"
  - name: "needs-reproduction"
    description: "Needs steps to reproduce"
    color: "f9d0c4"
  - name: "needs-investigation"
    description: "Needs investigation"
    color: "f9d0c4"
  - name: "needs-design"
    description: "Needs design work"
    color: "f9d0c4"
  - name: "needs-review"
    description: "Needs review"
    color: "f9d0c4"
  - name: "needs-testing"
    description: "Needs testing"
    color: "f9d0c4"
  - name: "needs-documentation"
    description: "Needs documentation"
    color: "f9d0c4"
  - name: "breaking-change"
    description: "Contains breaking changes"
    color: "d73a4a"
  - name: "security"
    description: "Security related"
    color: "d73a4a"
  - name: "performance"
    description: "Performance related"
    color: "fbca04"
  - name: "accessibility"
    description: "Accessibility related"
    color: "7057ff"
  - name: "internationalization"
    description: "Internationalization related"
    color: "7057ff"
  - name: "dependencies"
    description: "Dependencies related"
    color: "c5def5"
  - name: "github-actions"
    description: "GitHub Actions related"
    color: "2088ff"
  - name: "docker"
    description: "Docker related"
    color: "2496ed"
  - name: "javascript"
    description: "JavaScript related"
    color: "f7df1e"
  - name: "markdown"
    description: "Markdown related"
    color: "083fa1"
  - name: "yaml"
    description: "YAML related"
    color: "cb171e"
  - name: "json"
    description: "JSON related"
    color: "000000"
