name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run Prettier check
      run: npm run format:check

    - name: Check TypeScript
      run: npx tsc --noEmit

    - name: Check for TODO comments
      run: |
        if grep -r "TODO\|FIXME\|HACK" src/ --exclude-dir=node_modules; then
          echo "Found TODO/FIXME/HACK comments in code"
          exit 1
        fi

    - name: Check for console.log
      run: |
        if grep -r "console\.log" src/ --exclude-dir=node_modules; then
          echo "Found console.log statements in code"
          exit 1
        fi

    - name: Check for debugger statements
      run: |
        if grep -r "debugger" src/ --exclude-dir=node_modules; then
          echo "Found debugger statements in code"
          exit 1
        fi
