name: PR Assignee

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-assignee:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR assignee
      uses: actions/github-script@v7
      with:
        script: |
          const assignees = context.payload.pull_request.assignees;
          const reviewers = context.payload.pull_request.requested_reviewers;

          if (assignees.length === 0) {
            core.setFailed('PR must have at least one assignee');
            return;
          }

          if (reviewers.length === 0) {
            core.setFailed('PR must have at least one reviewer');
            return;
          }

          console.log(`PR has ${assignees.length} assignees and ${reviewers.length} reviewers`);
