name: PR Base Ref Force Pushed

on:
  pull_request:
    types: [base_ref_force_pushed]

jobs:
  pr-base-ref-force-pushed:
    runs-on: ubuntu-latest
    steps:
    - name: Handle base ref force pushed PR
      uses: actions/github-script@v8
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const status = pr.state;
          const draft = pr.draft;

          if (status !== 'open') {
            console.log('PR is not open');
            return;
          }

          if (draft) {
            console.log('PR is still in draft');
            return;
          }

          // Add base ref force pushed label
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['base-ref-force-pushed']
          });

          console.log('PR base ref force pushed');
