name: PR Head Ref Synchronize

on:
  pull_request:
    types: [head_ref_synchronize]

jobs:
  pr-head-ref-synchronize:
    runs-on: ubuntu-latest
    steps:
    - name: Handle head ref synchronize PR
      uses: actions/github-script@v8
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const status = pr.state;
          const draft = pr.draft;

          if (status !== 'open') {
            console.log('PR is not open');
            return;
          }

          if (draft) {
            console.log('PR is still in draft');
            return;
          }

          // Add head ref synchronize label
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['head-ref-synchronize']
          });

          console.log('PR head ref synchronize');
