name: PR Head Ref Restored

on:
  pull_request:
    types: [head_ref_restored]

jobs:
  pr-head-ref-restored:
    runs-on: ubuntu-latest
    steps:
    - name: Handle head ref restored PR
      uses: actions/github-script@v8
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const status = pr.state;
          const draft = pr.draft;

          if (status !== 'open') {
            console.log('PR is not open');
            return;
          }

          if (draft) {
            console.log('PR is still in draft');
            return;
          }

          // Remove head ref deleted label
          await github.rest.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            name: 'head-ref-deleted'
          });

          console.log('PR head ref restored');
