name: PR Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Check merge requirements
      uses: actions/github-script@v8
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const status = pr.state;
          const draft = pr.draft;
          const mergeable = pr.mergeable;
          const mergeableState = pr.mergeable_state;

          if (status !== 'open') {
            console.log('PR is not open');
            return;
          }

          if (draft) {
            console.log('PR is still in draft');
            return;
          }

          if (!mergeable) {
            console.log('PR is not mergeable');
            return;
          }

          if (mergeableState !== 'clean') {
            console.log(`PR mergeable state: ${mergeableState}`);
            return;
          }

          // Check if all required checks pass
          const { data: checks } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: pr.head.sha
          });

          const failedChecks = checks.check_runs.filter(c => c.conclusion === 'failure');

          if (failedChecks.length > 0) {
            console.log(`Failed checks: ${failedChecks.map(c => c.name).join(', ')}`);
            return;
          }

          // Check if PR has required labels
          const { data: labels } = await github.rest.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });

          const labelNames = labels.map(l => l.name);

          if (!labelNames.includes('status: ready-for-review')) {
            console.log('PR is not ready for review');
            return;
          }

          if (labelNames.includes('needs-review')) {
            console.log('PR still needs review');
            return;
          }

          console.log('PR is ready to merge');
