name: PR Review Requested Removed

on:
  pull_request:
    types: [review_request_removed]

jobs:
  pr-review-requested-removed:
    runs-on: ubuntu-latest
    steps:
    - name: Handle review request removed PR
      uses: actions/github-script@v8
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const status = pr.state;
          const draft = pr.draft;

          if (status !== 'open') {
            console.log('PR is not open');
            return;
          }

          if (draft) {
            console.log('PR is still in draft');
            return;
          }

          // Check if there are still reviewers
          const { data: reviewers } = await github.rest.pulls.listRequestedReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          if (reviewers.users.length === 0) {
            console.log('No reviewers left');

            // Remove needs review label
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'needs-review'
            });

            // Add ready for review label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['status: ready-for-review']
            });

          } else {
            console.log(`Still has ${reviewers.users.length} reviewers`);
          }
