name: PR Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-size:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Calculate PR size
      uses: actions/github-script@v7
      with:
        script: |
          const { data: files } = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const additions = files.reduce((acc, file) => acc + file.additions, 0);
          const deletions = files.reduce((acc, file) => acc + file.deletions, 0);
          const changes = additions + deletions;

          let size = 'xs';
          if (changes > 500) size = 'xl';
          else if (changes > 200) size = 'l';
          else if (changes > 50) size = 'm';
          else if (changes > 10) size = 's';

          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: [`size: ${size}`]
          });

          console.log(`PR size: ${size} (${changes} changes)`);
