name: PR Unlocked

on:
  pull_request:
    types: [unlocked]

jobs:
  pr-unlocked:
    runs-on: ubuntu-latest
    steps:
    - name: Handle unlocked PR
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const status = pr.state;
          const draft = pr.draft;

          if (status !== 'open') {
            console.log('PR is not open');
            return;
          }

          if (draft) {
            console.log('PR is still in draft');
            return;
          }

          // Remove locked label
          await github.rest.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            name: 'locked'
          });

          console.log('PR unlocked');
